net_param = "regtest"
# 日志级别，分别是debug, info, warn, error, critical
loglevel = "debug"

[BTC]
rpc_server = "127.0.0.1:8447"
rpc_user = ""
rpc_password = ""
confirm_block_num = 6
coinbase_confirm_block_num = 100

[BCH]
rpc_server = "127.0.0.1:8445"
rpc_user = ""
rpc_password = ""
confirm_block_num = 6
coinbase_confirm_block_num = 100


[LEVELDB]
btc_db_path = "/Users/user/leveldb_data/btc_tx_db"
bch_db_path = "/Users/user/leveldb_data/bch_tx_db"
ew_nonce_db_path = "/Users/user/leveldb_data/ew_tx_db"
eos_db_path = ""
[KEYSTORE]
url = "http://127.0.0.1:8976"
local_pubkey_hash = "3722834BCB13F7308C28907B69A99DB462F39036"
count = 4
key_0 = "04A2E82BE35D90D954E15CC5865E2F8AC22FD2DDBD4750F4BFC7596363A3451D1B75F4A8BAD28CF48F63595349DBC141D6D6E21F4FEB65BDC5E1A8382A2775E787"
key_1 = "049FD6230E3BADBBC7BA190E10B2FC5C3D8EA9B758A43E98AB2C8F83C826AE7EABEA6D88880BC606FA595CD8DD17FC7784B3E55D8EE0705045119545A803215B80"
key_2 = "044667E5B36F387C4D8D955C33FC271F46D791FD3433C0B2F517375BBD9AAE6B8C2392229537B109AC8EADCCE104AEAA64DB2D90BEF9008A09F8563CDB05FFB60B"
key_3 = "0402580DDB61E10132A58BA6E18F78DC62F522653C08AB9E0DFED8F08DF380D35EF29DA7A8DB1D72AB67851FA3BBE5C71DCDB82F3A7A8785A0A1E7B1F2B042939E"
service_id = "0daf7126-ebbb-4b2d-86f8-a480c1fd45a8"
keystore_private_key = "C51C9CB7A7EC9D12BB37B3700856690719A44056B750AB03A21247A4903BF3CB"

[DGW]
count = 4
local_id = 0
local_p2p_port = 10000
local_http_port = 8080
local_http_user = ""
local_http_pwd = ""
host_0 = "127.0.0.1:10000"
status_0 = true
host_1 = "127.0.0.1:10001"
status_1 = true
host_2 = "127.0.0.1:10002"
status_2 = true
host_3 = "127.0.0.1:10003"
status_3 = true
pprof_host = ":8060"

new_node_host = "127.0.0.1:10001"
new_node_pubkey = "049FD6230E3BADBBC7BA190E10B2FC5C3D8EA9B758A43E98AB2C8F83C826AE7EABEA6D88880BC606FA595CD8DD17FC7784B3E55D8EE0705045119545A803215B80"

bch_height = 1000000
btc_height = 1000000
eth_height = 10000000
dbpath = "/Users/user/leveldb_data/node0/dgateway"
eth_client_url = "ws://127.0.0.1:8830"
eos_dgateway_account = ""

# start_mode指定节点的启动方式，1是正常启动，利用配置文件里面的节点信息建立网关集群，2是加入已有网关集群, 3是以观察节点的方式启动
start_mode = 1
# init_node_host仅在mode!=1时才有意义，作为新节点的引导节点
init_node_host = "127.0.0.1:10000"
local_host = "127.0.0.1:10001"
local_pubkey = "049FD6230E3BADBBC7BA190E10B2FC5C3D8EA9B758A43E98AB2C8F83C826AE7EABEA6D88880BC606FA595CD8DD17FC7784B3E55D8EE0705045119545A803215B80"
#交易确认区块数
btc_confirms = 6
bch_confirms = 6 
#交易超时时间min
confirm_tolerance = 10
check_onchain_interval = 30
check_onchain_cur = 5
#accuse 间隔单位s
accuse_interval = 180
#锁定utxo的时间
utxo_lock_time = 60
tx_conn_pool_size = 100
block_coon_pool_size = 20

[METRICS]
need_metrics = false
# 每隔多久上报一次
interval = 100e6
influxdb_uri = "http://127.0.0.1:8086"
db = "test_metrics"
user = ""
password = ""

[ETHWATCHER]
vote_contract = ""
